

language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install poetry
  - poetry install
script:
  - black --check -v muggle/ test/
  - flake8 --ignore E501 muggle/ test/
  - pytest --cov muggle/ --cov-report xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
